FROM nginx

COPY ./site /usr/share/nginx/html

#COPY ./site/docs /usr/src/app/docs/docs
#CMD cd docs && mkdocs serve -a 0.0.0.0:8000

# very helpful documentation is here
# https://github.com/jupyter/docker-stacks/wiki/Docker-Recipes
# Install more python 2 packages
# upgrading to 0.0.3 python package
#RUN bash -c "source activate python2 && pip install -U --extra-index-url http://pypi.pointwise.co:8080/simple --trusted-host pypi.pointwise.co dm_utils_data_regularity==$DM_UTILS_VERSION"

